import numpy as np
a1=np.array([10,20,30,40])
a2=np.array([50,20,70,40])

L1=[10,20,30,40]
L2=[50,60,70,80]

a1,a2,L1,L2

## Differences in between python list and numpy array

# + operator

In [7]:
a1+a2   #adds Respective elements if dimensions are same

array([ 60,  40, 100,  80])

In [8]:
L1+L2   #concatenate 2 lists

[10, 20, 30, 40, 50, 60, 70, 80]

In [9]:
a1+100  #adds 100 in each element of array

array([110, 120, 130, 140])

In [10]:
L1 + 100  #Error: Data types should be same

TypeError: can only concatenate list (not "int") to list

# * operator

In [ ]:
a1*a2    #multiplies all the elements

In [ ]:
L1*L2 #Replication: multiplier should be an integer

In [ ]:
a1*2  #multiplies with 2 to all the elements of a1

In [ ]:
L1*2  #Replicates list elements with 2

In [ ]:
a1*3.5

In [ ]:
L1*3.5 #multiplier should be an integer

In [ ]:
a1**2 #squares the elements a1

In [ ]:
L1**2 #Error

# / operator

In [ ]:
a1/2  #Divides each element of a1 by 2

In [ ]:
L1/2

In [ ]:
a1//2 #Integer Division

# % operator

In [ ]:
a1%3 

In [ ]:
L1%3

# - operator

In [14]:
a2-a1 #Substracts respective elements of the array

array([40,  0, 40,  0])

In [16]:
L2-L1

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [17]:
a3=np.array([10,11.8,'Hi'])# It converts all elements into string(possible data type conversion)
a3

array(['10', '11.8', 'Hi'], dtype='<U32')

In [18]:
## 2-D array

a2=np.array([[10,20,30],[40,50,60],[70,80,90]])

a2.shape #Number of rows and colsy

(3, 3)

In [19]:
a2.size # product of row * col/Total elements present in array

9

In [20]:
a2.ndim #number of dimensions

2

In [21]:
a1.ndim

1

In [22]:
a2.dtype #It returns data type of items in array

dtype('int32')

In [11]:
a2.astype('float64') #It converts data type to a specified type

array([50., 20., 70., 40.])

In [12]:
a2.tolist() #Convert array to a Python list

[50, 20, 70, 40]

In [13]:
np.info(a2)#It returns an information about array

class:  ndarray
shape:  (4,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x204f3488ef0
byteorder:  little
byteswap:  False
type: int32


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
z=np.zeros((4,5),dtype='int32')
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
on=np.ones((4,4))
on

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
tw=np.ones((3,3),dtype='int32')*2
tw

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
th=np.ones((3,3),dtype='int32')*3
th

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [9]:
any_arr=np.full((5,8), 5)
any_arr

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [10]:
ey=np.eye(7,dtype='int32')#Identity Matrix
ey

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [34]:
for i in range(1,11, 100):
    print(i)

1


In [27]:
L=np.linspace(1,10, 100) #It splits a given range into equally spaced partitions
len(L),L

(100,
 array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
         1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
         2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
         3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
         4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
         5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
         6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [28]:
np.linspace(1.3,10.3,30)

array([ 1.3       ,  1.61034483,  1.92068966,  2.23103448,  2.54137931,
        2.85172414,  3.16206897,  3.47241379,  3.78275862,  4.09310345,
        4.40344828,  4.7137931 ,  5.02413793,  5.33448276,  5.64482759,
        5.95517241,  6.26551724,  6.57586207,  6.8862069 ,  7.19655172,
        7.50689655,  7.81724138,  8.12758621,  8.43793103,  8.74827586,
        9.05862069,  9.36896552,  9.67931034,  9.98965517, 10.3       ])

In [8]:
for i in range(1,11,2.5):print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
for i in range(1,11,1.5):#normal range will not allow us to use floating point numbers
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [40]:
np.arange(1, 11, 1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [9]:
np.arange(1.3, 11, 2) #Note: np.arange allows us to use floating point numbers also

array([1.3, 3.3, 5.3, 7.3, 9.3])

In [5]:
for i in np.arange(1.3, 11, 2):
    print(i)

1.3
3.3
5.3
7.299999999999999
9.299999999999999


In [55]:
np.random.rand(4,5) #only +ve value in the range(0,1)

array([[0.00726736, 0.9851591 , 0.43065629, 0.65808431, 0.96299652],
       [0.05749488, 0.41243745, 0.12955752, 0.77443407, 0.46238381],
       [0.66681704, 0.97865982, 0.48813852, 0.6426254 , 0.65737003],
       [0.78708456, 0.83510423, 0.86198065, 0.87385771, 0.11337796]])

In [9]:
np.random.randn(4,5) #it includes +ve and -ve values with median

array([[-2.34403196,  0.80750355, -0.32456411,  0.2101258 , -0.18872592],
       [-0.42916526,  0.8845959 ,  2.52496935, -0.25322143,  0.39761548],
       [ 0.34519702, -0.23681638, -1.1207164 ,  1.15470522, -0.59267164],
       [-1.15635446, -0.59243035,  0.43614146,  2.03367001,  1.24857161]])

In [57]:
np.random.rand(6,7)*100

array([[28.4181113 , 23.33210911, 88.40252262, 87.63702715, 65.08491413,
        12.33952611, 87.32442627],
       [87.64935165, 57.98503207, 19.35240971, 27.19862165, 38.95983069,
        14.90015225, 16.66115844],
       [12.04033485, 14.498838  , 17.27133423, 33.54641037,  7.91915618,
        83.81230299,  4.65224691],
       [31.98445377, 25.76799408, 53.64261601, 80.66475384, 77.6361631 ,
        19.39314305, 39.58806824],
       [31.08434182, 47.45322171, 51.70540448, 60.18688835, 59.3930365 ,
        80.68995467, 71.68399073],
       [ 1.19757827, 64.76323298, 27.24815795, 19.13488409, 80.17991862,
        84.70743557, 48.84645745]])

In [58]:
L=np.random.rand(3,3)
L

array([[0.59638548, 0.56989726, 0.06642505],
       [0.65983796, 0.56786403, 0.67869565],
       [0.61026839, 0.80797222, 0.1378889 ]])

In [59]:
L*100

array([[59.63854807, 56.98972602,  6.64250462],
       [65.98379597, 56.78640263, 67.86956542],
       [61.0268388 , 80.79722244, 13.78889043]])

In [11]:
h=np.random.randint(60,130,size=(5,5))
h

array([[ 96,  86, 120, 117, 121],
       [ 71,  73,  72,  78,  85],
       [ 77,  78, 122,  60,  77],
       [ 88, 111,  77,  70,  94],
       [ 77,  94,  99, 100,  69]])

In [13]:
data=np.random.randint(3,30,size=(5,5))
data

array([[15, 25, 25,  9, 18],
       [25,  8, 18,  8, 27],
       [28,  7,  5,  3, 23],
       [12, 20, 29, 10,  6],
       [25, 18,  7, 25, 10]])

In [14]:
data.size#product of row*cols

25

In [15]:
data.dtype#returns data type of elements

dtype('int32')

In [16]:
data=data.astype('int64')#astype=>It converts elements to given datatype

In [14]:
data.dtype

dtype('int64')

In [17]:
data.astype('float64')

array([[15., 25., 25.,  9., 18.],
       [25.,  8., 18.,  8., 27.],
       [28.,  7.,  5.,  3., 23.],
       [12., 20., 29., 10.,  6.],
       [25., 18.,  7., 25., 10.]])

In [18]:
lt=data.tolist()
lt

[[15, 25, 25, 9, 18],
 [25, 8, 18, 8, 27],
 [28, 7, 5, 3, 23],
 [12, 20, 29, 10, 6],
 [25, 18, 7, 25, 10]]

In [19]:
np.info(data)

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2e187bf6290
byteorder:  little
byteswap:  False
type: int64


In [20]:
data=data.astype('float')
data

array([[15., 25., 25.,  9., 18.],
       [25.,  8., 18.,  8., 27.],
       [28.,  7.,  5.,  3., 23.],
       [12., 20., 29., 10.,  6.],
       [25., 18.,  7., 25., 10.]])

In [21]:
data.dtype

dtype('float64')

In [22]:
data.view('int64')

array([[4624633867356078080, 4627730092099895296, 4627730092099895296,
        4621256167635550208, 4625759767262920704],
       [4627730092099895296, 4620693217682128896, 4625759767262920704,
        4620693217682128896, 4628293042053316608],
       [4628574517030027264, 4619567317775286272, 4617315517961601024,
        4613937818241073152, 4627167142146473984],
       [4622945017495814144, 4626322717216342016, 4628855992006737920,
        4621819117588971520, 4618441417868443648],
       [4627730092099895296, 4625759767262920704, 4619567317775286272,
        4627730092099895296, 4621819117588971520]], dtype=int64)

In [23]:
data=data.astype('int64')
data

array([[15, 25, 25,  9, 18],
       [25,  8, 18,  8, 27],
       [28,  7,  5,  3, 23],
       [12, 20, 29, 10,  6],
       [25, 18,  7, 25, 10]], dtype=int64)

In [24]:
data.sort() #row-wise sorting

In [25]:
data

array([[ 9, 15, 18, 25, 25],
       [ 8,  8, 18, 25, 27],
       [ 3,  5,  7, 23, 28],
       [ 6, 10, 12, 20, 29],
       [ 7, 10, 18, 25, 25]], dtype=int64)

In [26]:
data.sort(axis=0)#column-wise sorting
data

array([[ 3,  5,  7, 20, 25],
       [ 6,  8, 12, 23, 25],
       [ 7, 10, 18, 25, 27],
       [ 8, 10, 18, 25, 28],
       [ 9, 15, 18, 25, 29]], dtype=int64)

In [27]:
data.flatten() # converting 2D array to 1D

array([ 3,  5,  7, 20, 25,  6,  8, 12, 23, 25,  7, 10, 18, 25, 27,  8, 10,
       18, 25, 28,  9, 15, 18, 25, 29], dtype=int64)

In [23]:
data.T #Transpose: rows becomes columns and vice-versa

NameError: name 'data' is not defined

In [24]:
data

NameError: name 'data' is not defined

In [25]:
ex=np.random.randint(10,30,size=(3,4))
ex

array([[28, 22, 16, 16],
       [13, 24, 20, 23],
       [26, 10, 23, 16]])

In [31]:
ex.reshape(4,3)

array([[15, 19, 13],
       [13, 12, 18],
       [18, 23, 14],
       [13, 15, 11]])

In [26]:
ex.reshape(2,6)

array([[28, 22, 16, 16, 13, 24],
       [20, 23, 26, 10, 23, 16]])

In [65]:
ex.reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [24]:
np.resize(ex,(4,4))

array([[17, 28, 16, 13],
       [20, 14, 19, 16],
       [23, 27, 10, 29],
       [17, 28, 16, 13]])

In [33]:
np.resize(data,(5,6))

array([[ 3,  5,  7, 20, 25,  6],
       [ 8, 12, 23, 25,  7, 10],
       [18, 25, 27,  8, 10, 18],
       [25, 28,  9, 15, 18, 25],
       [29,  3,  5,  7, 20, 25]], dtype=int64)

In [34]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [84]:
arr=np.append(arr,10)
arr

array([ 1,  2,  3, 10])

In [35]:
ex

array([[15, 19, 13, 13],
       [12, 18, 18, 23],
       [14, 13, 15, 11]])

In [36]:
np.delete(ex,2,axis=1) #deletes col 2 from array

array([[15, 19, 13],
       [12, 18, 23],
       [14, 13, 11]])

In [37]:
np.delete(ex,2,axis=0)#deletes row 2 from array

array([[15, 19, 13, 13],
       [12, 18, 18, 23]])

In [40]:
data

array([[ 3,  5,  7, 20, 25],
       [ 6,  8, 12, 23, 25],
       [ 7, 10, 18, 25, 27],
       [ 8, 10, 18, 25, 28],
       [ 9, 15, 18, 25, 29]], dtype=int64)

In [16]:
h

NameError: name 'h' is not defined

In [17]:
np.concatenate((data,h),axis=0) #row-wise 

NameError: name 'data' is not defined

In [42]:
np.concatenate((data,h),axis=1) #col-wise

array([[  3,   5,   7,  20,  25,  96,  86, 120, 117, 121],
       [  6,   8,  12,  23,  25,  71,  73,  72,  78,  85],
       [  7,  10,  18,  25,  27,  77,  78, 122,  60,  77],
       [  8,  10,  18,  25,  28,  88, 111,  77,  70,  94],
       [  9,  15,  18,  25,  29,  77,  94,  99, 100,  69]], dtype=int64)

In [45]:
np.split(h,5) #row-wise split

[array([[ 96,  86, 120, 117, 121]]),
 array([[71, 73, 72, 78, 85]]),
 array([[ 77,  78, 122,  60,  77]]),
 array([[ 88, 111,  77,  70,  94]]),
 array([[ 77,  94,  99, 100,  69]])]

In [46]:
np.hsplit(h,5)#col-wise split

[array([[96],
        [71],
        [77],
        [88],
        [77]]),
 array([[ 86],
        [ 73],
        [ 78],
        [111],
        [ 94]]),
 array([[120],
        [ 72],
        [122],
        [ 77],
        [ 99]]),
 array([[117],
        [ 78],
        [ 60],
        [ 70],
        [100]]),
 array([[121],
        [ 85],
        [ 77],
        [ 94],
        [ 69]])]

In [47]:
h

array([[ 96,  86, 120, 117, 121],
       [ 71,  73,  72,  78,  85],
       [ 77,  78, 122,  60,  77],
       [ 88, 111,  77,  70,  94],
       [ 77,  94,  99, 100,  69]])

In [48]:
h[0]

array([ 96,  86, 120, 117, 121])

In [49]:
h[0][2]

120

In [50]:
h[0,2] #Hash the values of 0th row and 2nd col--> [row, col] 

120

In [51]:
#arr[rowindex,colindex]

h[::2, :]

array([[ 96,  86, 120, 117, 121],
       [ 77,  78, 122,  60,  77],
       [ 77,  94,  99, 100,  69]])

In [52]:
h[1::2, ::2]

array([[71, 72, 85],
       [88, 77, 94]])

In [54]:
h>75

array([[ True,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [56]:
h [h>75] #It will filter the data where values are greater than 75

array([ 96,  86, 120, 117, 121,  78,  85,  77,  78, 122,  77,  88, 111,
        77,  94,  77,  94,  99, 100])

In [57]:
h

array([[ 96,  86, 120, 117, 121],
       [ 71,  73,  72,  78,  85],
       [ 77,  78, 122,  60,  77],
       [ 88, 111,  77,  70,  94],
       [ 77,  94,  99, 100,  69]])

In [58]:
~h #Inverse of Matrix

array([[ -97,  -87, -121, -118, -122],
       [ -72,  -74,  -73,  -79,  -86],
       [ -78,  -79, -123,  -61,  -78],
       [ -89, -112,  -78,  -71,  -95],
       [ -78,  -95, -100, -101,  -70]])

In [59]:
h

array([[ 96,  86, 120, 117, 121],
       [ 71,  73,  72,  78,  85],
       [ 77,  78, 122,  60,  77],
       [ 88, 111,  77,  70,  94],
       [ 77,  94,  99, 100,  69]])

In [60]:
h+10

array([[106,  96, 130, 127, 131],
       [ 81,  83,  82,  88,  95],
       [ 87,  88, 132,  70,  87],
       [ 98, 121,  87,  80, 104],
       [ 87, 104, 109, 110,  79]])

In [61]:
h.sum()

2212

In [62]:
h.min()

60

In [63]:
h.max()

122

In [64]:
h.max(axis=1)#Max values in individual columns

array([121,  85, 122, 111, 100])

In [65]:
h.max(axis=0)#Max values in individual rows

array([ 96, 111, 122, 117, 121])

In [66]:
a1==a2

C:\Users\Shree\AppData\Local\Temp\ipykernel_7656\3426729955.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  a1==a2


False

In [67]:
np.array_equal(a1,a2)

False

In [68]:
a3=np.array(L1)
a3,a1

(array([10, 20, 30, 40]), array([10, 20, 30, 40]))

In [69]:
np.array_equal(a1,a3)

True

In [70]:
a1==a3

array([ True,  True,  True,  True])

In [71]:
h

array([[ 96,  86, 120, 117, 121],
       [ 71,  73,  72,  78,  85],
       [ 77,  78, 122,  60,  77],
       [ 88, 111,  77,  70,  94],
       [ 77,  94,  99, 100,  69]])

In [72]:
np.transpose(h)

array([[ 96,  71,  77,  88,  77],
       [ 86,  73,  78, 111,  94],
       [120,  72, 122,  77,  99],
       [117,  78,  60,  70, 100],
       [121,  85,  77,  94,  69]])

In [73]:
np.sqrt(a1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [74]:
np.floor(np.sqrt(a1))

array([3., 4., 5., 6.])

In [75]:
h.T

array([[ 96,  71,  77,  88,  77],
       [ 86,  73,  78, 111,  94],
       [120,  72, 122,  77,  99],
       [117,  78,  60,  70, 100],
       [121,  85,  77,  94,  69]])

In [76]:
h.ravel()

array([ 96,  86, 120, 117, 121,  71,  73,  72,  78,  85,  77,  78, 122,
        60,  77,  88, 111,  77,  70,  94,  77,  94,  99, 100,  69])

In [77]:
h.flatten()

array([ 96,  86, 120, 117, 121,  71,  73,  72,  78,  85,  77,  78, 122,
        60,  77,  88, 111,  77,  70,  94,  77,  94,  99, 100,  69])

## reading csv file using numpy

In [3]:
data=np.genfromtxt("Auto.csv",delimiter=',')
data[:5]

array([[      nan,       nan,       nan,       nan,       nan,       nan,
              nan,       nan,       nan],
       [1.800e+01, 8.000e+00, 3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01,
        7.000e+01, 1.000e+00,       nan],
       [1.500e+01, 8.000e+00, 3.500e+02, 1.650e+02, 3.693e+03, 1.150e+01,
        7.000e+01, 1.000e+00,       nan],
       [1.800e+01, 8.000e+00, 3.180e+02, 1.500e+02, 3.436e+03, 1.100e+01,
        7.000e+01, 1.000e+00,       nan],
       [1.600e+01, 8.000e+00, 3.040e+02, 1.500e+02, 3.433e+03, 1.200e+01,
        7.000e+01, 1.000e+00,       nan]])

**nan** means **n**ot **a n**umber

It is an standard missing data marker used in data analysis

In [4]:
data=data[1:]
data

array([[ 18.,   8., 307., ...,  70.,   1.,  nan],
       [ 15.,   8., 350., ...,  70.,   1.,  nan],
       [ 18.,   8., 318., ...,  70.,   1.,  nan],
       ...,
       [ 32.,   4., 135., ...,  82.,   1.,  nan],
       [ 28.,   4., 120., ...,  82.,   1.,  nan],
       [ 31.,   4., 119., ...,  82.,   1.,  nan]])

In [5]:
data=data[:,:-1]
data

array([[ 18. ,   8. , 307. , ...,  12. ,  70. ,   1. ],
       [ 15. ,   8. , 350. , ...,  11.5,  70. ,   1. ],
       [ 18. ,   8. , 318. , ...,  11. ,  70. ,   1. ],
       ...,
       [ 32. ,   4. , 135. , ...,  11.6,  82. ,   1. ],
       [ 28. ,   4. , 120. , ...,  18.6,  82. ,   1. ],
       [ 31. ,   4. , 119. , ...,  19.4,  82. ,   1. ]])

In [8]:
len(data)

392

In [9]:
data.ndim

2

In [10]:
data.shape

(392, 8)

In [16]:
text=np.loadtxt("file_demo.txt",dtype="object")
text

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'abc'],
      dtype=object)

In [17]:
data

array([[ 18. ,   8. , 307. , ...,  12. ,  70. ,   1. ],
       [ 15. ,   8. , 350. , ...,  11.5,  70. ,   1. ],
       [ 18. ,   8. , 318. , ...,  11. ,  70. ,   1. ],
       ...,
       [ 32. ,   4. , 135. , ...,  11.6,  82. ,   1. ],
       [ 28. ,   4. , 120. , ...,  18.6,  82. ,   1. ],
       [ 31. ,   4. , 119. , ...,  19.4,  82. ,   1. ]])

In [19]:
sample=data[:10]

In [24]:
np.hsplit(sample,(10,0))

[array([[1.800e+01, 8.000e+00, 3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01,
         7.000e+01, 1.000e+00],
        [1.500e+01, 8.000e+00, 3.500e+02, 1.650e+02, 3.693e+03, 1.150e+01,
         7.000e+01, 1.000e+00],
        [1.800e+01, 8.000e+00, 3.180e+02, 1.500e+02, 3.436e+03, 1.100e+01,
         7.000e+01, 1.000e+00],
        [1.600e+01, 8.000e+00, 3.040e+02, 1.500e+02, 3.433e+03, 1.200e+01,
         7.000e+01, 1.000e+00],
        [1.700e+01, 8.000e+00, 3.020e+02, 1.400e+02, 3.449e+03, 1.050e+01,
         7.000e+01, 1.000e+00],
        [1.500e+01, 8.000e+00, 4.290e+02, 1.980e+02, 4.341e+03, 1.000e+01,
         7.000e+01, 1.000e+00],
        [1.400e+01, 8.000e+00, 4.540e+02, 2.200e+02, 4.354e+03, 9.000e+00,
         7.000e+01, 1.000e+00],
        [1.400e+01, 8.000e+00, 4.400e+02, 2.150e+02, 4.312e+03, 8.500e+00,
         7.000e+01, 1.000e+00],
        [1.400e+01, 8.000e+00, 4.550e+02, 2.250e+02, 4.425e+03, 1.000e+01,
         7.000e+01, 1.000e+00],
        [1.500e+01, 8.000e+00, 3.900e

In [27]:
np.vsplit(sample,(8,1))

[array([[1.800e+01, 8.000e+00, 3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01,
         7.000e+01, 1.000e+00],
        [1.500e+01, 8.000e+00, 3.500e+02, 1.650e+02, 3.693e+03, 1.150e+01,
         7.000e+01, 1.000e+00],
        [1.800e+01, 8.000e+00, 3.180e+02, 1.500e+02, 3.436e+03, 1.100e+01,
         7.000e+01, 1.000e+00],
        [1.600e+01, 8.000e+00, 3.040e+02, 1.500e+02, 3.433e+03, 1.200e+01,
         7.000e+01, 1.000e+00],
        [1.700e+01, 8.000e+00, 3.020e+02, 1.400e+02, 3.449e+03, 1.050e+01,
         7.000e+01, 1.000e+00],
        [1.500e+01, 8.000e+00, 4.290e+02, 1.980e+02, 4.341e+03, 1.000e+01,
         7.000e+01, 1.000e+00],
        [1.400e+01, 8.000e+00, 4.540e+02, 2.200e+02, 4.354e+03, 9.000e+00,
         7.000e+01, 1.000e+00],
        [1.400e+01, 8.000e+00, 4.400e+02, 2.150e+02, 4.312e+03, 8.500e+00,
         7.000e+01, 1.000e+00]]),
 array([], shape=(0, 8), dtype=float64),
 array([[1.500e+01, 8.000e+00, 3.500e+02, 1.650e+02, 3.693e+03, 1.150e+01,
         7.000e+01, 1.000e